# Change these first
owner: stamateas # Your GitHub username
repo: upptime # Your GitHub repository name

#Add your sites here
sites:
  - name: Recatt Server
    url: https://recatt.its-telekom.eu
    maxResponseTime: 2000
  - name: GitLab Server
    url: https://gitlab01.its-telekom.eu
    maxResponseTime: 2000
  - name: Jenkins Server
    url: https://jenkins01.its-telekom.eu/
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 403
    maxResponseTime: 2000
  - name: ReportPortal Server
    url: https://reporting.its-telekom.eu/
    maxResponseTime: 2000
  - name: Authentication Server
    url: https://auth.its-telekom.eu/
    maxResponseTime: 2000
  - name: Mattermost Server
    url: https://mattermost.its-telekom.eu/
    maxResponseTime: 2000
  - name: Proxima/DNS Server
    url: http://proxima01.its-telekom.eu/
    maxResponseTime: 2000
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Test for HEAD
#    method: HEAD
#    url: https://www.google.com
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.its-telekom.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Server Status
  introTitle: "IVA Test Automation Server Status"
  introMessage: 
  navbar:
    - title: Server Status
      href: /
  #  - title: Home
  #    href: https://recatt.its-telekom.eu/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


i18n:
  footer: This page is [open source]($REPO), powered by Test Automation @ IVA
  liveStatus: Server Status
  allSystemsOperational: All Servers are operational! 
